---
- name: 
  hosts:  
  become: true
  roles:
    - role: packages
      basepackages:
        - perl-DateTime
        - perl-Sys-Syslog
        - perl-LWP-Protocol-https
        - perl-Digest-SHA.x86_64
        - unzip
      basepackages_remove:
        - ipchains
        - kernel-source
        - firewalld 
    - cloudEndureAgent
    - awsCli
    - cloudWatchAgent
    - ssm
    - nitroDriverInstall
    - ssmMonitorScript
