---
language: python
services: docker

env:
  global:
    - ROLE_NAME: amazon-cloudwatch-agent
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: amazonlinux:2
    - MOLECULE_DISTRO: amazonlinux:1
    - MOLECULE_DISTRO: ubuntu-14.04
    - MOLECULE_DISTRO: ubuntu-16.04
    - MOLECULE_DISTRO: ubuntu-18.04
    - MOLECULE_DISTRO: ubuntu-18.10
install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
