---
- name: Disable network manager using UnmanageDNS.conf
  copy:
    src: UnmanageDNS.conf
    dest: /etc/NetworkManager/conf.d/UnmanageDNS.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart networkmanager
  tags: dns

- name: Configure resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
  tags: dns
